Updated package build to use crankstart.

diff --git a/contrib/launchpad/debian/src/root_fs/etc/init.d/sling b/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
--- a/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
+++ b/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
@@ -26,50 +26,60 @@
 # Description:       Enable service provided by sling.
 ### END INIT INFO
 
+. /etc/profile
+export FANCYTTY=true
+. /lib/lsb/init-functions
+export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
+SLING_DEFAULTS=/etc/default/sling
+if [ -r $SLING_DEFAULTS ] ; then
+	. $SLING_DEFAULTS
+else
+	log_failure_msg "Missing $SLING_DEFAULTS file, cannot read env settings."
+	exit -1
+fi
+
 #
 # Usage
 #
 function usage () {
-   echo "Purpose: Stop/Start sling"
-   echo "Usage  : $0 { stop | start }"
+	log_warning_msg "Purpose: Stop/Start sling"
+	log_warning_msg "Usage  : $0 { stop | start | restart }"
 }
-
-NAME=sling
-
-PID=/var/run/${NAME}.pid
 
 [ "$DEBUG" ] && set -x
 
-. /etc/profile
+NAME=sling
+PID=/var/run/${NAME}.pid
+DAEMON=$(which java)
 
-export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
 
-SLING_DEFAULTS=/etc/default/sling
-[ -r $SLING_DEFAULTS ] && . $SLING_DEFAULTS
+[ -r $CRANKSTART_ENV ] && . $CRANKSTART_ENV
+CRANKSTART_JAR=${M2REPO}/crankstart.jar
 
-SLING_JAR=$(find $SLING_HOME -name \*-standalone.jar)
+# running()
+# {
+# 	local PID=$(cat "$1" 2>/dev/null) || return 1
+# 	kill -0 "$PID" 2>/dev/null
+# }
 
-running()
-{
-  local PID=$(cat "$1" 2>/dev/null) || return 1
-  kill -0 "$PID" 2>/dev/null
-}
+# status()
+# {
+# 	if running "$PID"
+# 		then
+# 		echo "OK"
+# 	else
+# 		echo "FAILED"
+# 	fi
+# }
 
-status()
-{
-	if running "$PID"
-	then
-	  echo "OK"
-	else
-	  echo "FAILED"
-	fi
-}
+
 
 #
 # Stop current sling instance
 #
 function stop () {
-	start-stop-daemon --stop --chuid $SLING_USER:$SLING_GROUP --pidfile $PID --chdir $SLING_HOME --startas "./$NAME" --signal TERM
+	killproc -p $PID $DAEMON TERM
+#	start-stop-daemon --stop --chuid $SLING_USER:$SLING_GROUP --pidfile $PID --chdir $SLING_HOME --startas "./$NAME" --signal TERM
 }
 
 #
@@ -77,27 +87,34 @@ function stop () {
 #
 function start () {
 
-  if start-stop-daemon --start \
-	  --chdir "$SLING_HOME" \
-	  --chuid $SLING_USER \
-	  --pidfile "$PID" \
-	  --make-pidfile \
-	  --startas $(which java) \
-	  -- \
-	  $JAVA_ARGS $JAVA_DEBUG_ARGS \
-	  -jar $SLING_JAR $SLING_DEFAULT_ARGS \
-	  >>$LOG_FILE 2>&1 &
-  then
-	sleep 3s
-	status
-  fi
+	log_daemon_msg "Starting sling serices" "sling"
+	echo M2REPO=$M2REPO
+	if start-stop-daemon --start \
+		--chdir "$SLING_HOME" \
+		--chuid $SLING_USER \
+		--pidfile "$PID" \
+		--make-pidfile \
+		--background \
+		--startas $(which java) \
+		-- \
+		${JAVA_ARGS} \
+		${MVN_OPTS} \
+		-jar ${CRANKSTART_JAR} \
+		${SLING_CFG}/target/${RUNMODE}.txt
+		>>$LOG_FILE 2>&1 &
+	then
+		sleep 3s
+		status
+	fi
+	log_end_msg 0
 
 }
 
 if test -z "$1"; then
-   usage
-   exit
+	usage
+	exit
 fi
+
 case $1 in
 	start)
 		start
@@ -108,24 +125,26 @@ case $1 in
 	restart)
 		if [ -f $PID ] ; then
 			stop
-			while ps --pid $(cat $PID) >/dev/null ; do
+#			while ps --pid $(cat $PID) >/dev/null ; do
+			while pidofproc -p $PID $DAEMON ; do
 				sleep 1
 			done
 		fi
 		start
-		;;
+	;;
 	status)
-		if [ $(status) == "OK" ] ; then
-			exit 0
-		else
-			exit 1
-		fi
+		# if [ $(status) == "OK" ] ; then
+		# 	exit 0
+		# else
+		# 	exit 1
+		# fi
+		status_of_proc -p PID $DAEMON
 		;;
 	*)
 		echo "Unknown parameter: $1"
 		usage
 		;;
-	esac
+esac
 
 
 # end_of_file
