Initialization cleanup under crankstart.

diff --git a/contrib/launchpad/debian/src/root_fs/etc/init.d/sling b/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
--- a/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
+++ b/contrib/launchpad/debian/src/root_fs/etc/init.d/sling
@@ -31,6 +31,7 @@ export FANCYTTY=true
 . /lib/lsb/init-functions
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
 SLING_DEFAULTS=/etc/default/sling
+[ "$DEBUG" ] && set -x
 if [ -r $SLING_DEFAULTS ] ; then
 	. $SLING_DEFAULTS
 else
@@ -38,75 +39,79 @@ else
 	exit -1
 fi
 
-#
-# Usage
-#
+PID=/var/run/sling.pid
+DAEMON=$(which java)
+
 function usage () {
 	log_warning_msg "Purpose: Stop/Start sling"
 	log_warning_msg "Usage  : $0 { stop | start | restart }"
 }
 
-[ "$DEBUG" ] && set -x
-
-NAME=sling
-PID=/var/run/${NAME}.pid
-DAEMON=$(which java)
-
-
-[ -r $CRANKSTART_ENV ] && . $CRANKSTART_ENV
-CRANKSTART_JAR=${M2REPO}/crankstart.jar
-
-# running()
-# {
-# 	local PID=$(cat "$1" 2>/dev/null) || return 1
-# 	kill -0 "$PID" 2>/dev/null
-# }
-
-# status()
-# {
-# 	if running "$PID"
-# 		then
-# 		echo "OK"
-# 	else
-# 		echo "FAILED"
-# 	fi
-# }
-
-
-
-#
-# Stop current sling instance
-#
-function stop () {
-	killproc -p $PID $DAEMON TERM
-#	start-stop-daemon --stop --chuid $SLING_USER:$SLING_GROUP --pidfile $PID --chdir $SLING_HOME --startas "./$NAME" --signal TERM
+function rebuild_config () {
+	log_progress_msg "Rebuild configuration"
+	cd ${SLING_CFG}
+	make -e target/${RUNMODE}.txt
 }
 
-#
-# Start batch job scheduler
-#
+function stop () {
+	killproc -p $PID $DAEMON TERM
+}
+
+# Make sure premissions & directoreis are OK.
+function check_permissions() {
+	for d in SLING_DATA SLING_EXEC SLING_CFG SLING_LOG_DIR ; do
+		eval n=\$$d
+		if [ ! "${n}" ] ; then
+			log_failure_msg "Missing $d"
+			exit -1
+		fi
+		if [ ! -d ${n} ] ; then
+			echo "Fix type of ${n}"
+			rm -rf ${n}
+			install --directory --owner=${SLING_USER} --group=${SLING_GROUP} ${n}
+		else
+			if [ "$(stat -c '%U' ${n})" != "${SLING_USER}" ] ; then
+				echo "Update ownership of ${n}"
+				chown -R ${SLING_USER}:${SLING_GROUP} ${n}
+			fi
+		fi
+	done
+}
+
 function start () {
 
-	log_daemon_msg "Starting sling serices" "sling"
-	echo M2REPO=$M2REPO
+	check_permissions
+
+	# Get MVN_OPTS from crankstart env file.
+	[ -r $CRANKSTART_ENV ] && . $CRANKSTART_ENV
+	CRANKSTART_JAR=${M2REPO}/crankstart.jar
+
+	# Update crankstart file if needed
+	log_daemon_msg "Starting sling serices"
+	rebuild_config
+
+	log_progress_msg "Start sling daemon"
 	if start-stop-daemon --start \
-		--chdir "$SLING_HOME" \
+		--chdir "$SLING_EXEC" \
 		--chuid $SLING_USER \
 		--pidfile "$PID" \
 		--make-pidfile \
 		--background \
-		--startas $(which java) \
+		--verbose \
+		--no-close \
+		--exec $(which java) \
+		--start \
 		-- \
 		${JAVA_ARGS} \
 		${MVN_OPTS} \
 		-jar ${CRANKSTART_JAR} \
-		${SLING_CFG}/target/${RUNMODE}.txt
-		>>$LOG_FILE 2>&1 &
+		${SLING_CFG}/target/${RUNMODE}.txt \
+		>>$LOG_FILE 2>&1
 	then
-		sleep 3s
-		status
+		sleep 3
+		status_of_proc -p $PID $DAEMON
 	fi
-	log_end_msg 0
+	log_end_msg $?
 
 }
 
@@ -125,7 +130,6 @@ case $1 in
 	restart)
 		if [ -f $PID ] ; then
 			stop
-#			while ps --pid $(cat $PID) >/dev/null ; do
 			while pidofproc -p $PID $DAEMON ; do
 				sleep 1
 			done
@@ -133,18 +137,10 @@ case $1 in
 		start
 	;;
 	status)
-		# if [ $(status) == "OK" ] ; then
-		# 	exit 0
-		# else
-		# 	exit 1
-		# fi
-		status_of_proc -p PID $DAEMON
+		status_of_proc -p $PID $DAEMON
 		;;
 	*)
 		echo "Unknown parameter: $1"
 		usage
 		;;
 esac
-
-
-# end_of_file
